
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all",
    data = glob([
        "**/*.txt",
        "**/*.json",
        "**/*.yml",
        "**/*.yaml",
        "**/*.checkpoint",
        "**/*.npy",
    ]),
)
