imagePullSecrets:
- nvcrio

defaults:
  # localImage: bazel/sandbox/williamz/secret_project/docker:image
  localImage: bazel/sandbox/williamz/detr/docker:image
  # localImage: bazel/detr/docker:detr_image
  # localImage: bazel/dlav/common:image
  inputs:
    volumes:
      - name: split-outputs
        version: 8493af65-a8ff-5489-b876-d2695b855014
        mountPath: /drivenet_1
      - name: d3l-detection-f-train
        version: 2020-03-10-16-13-7945
        mountPath: /drivenet_2
      - name: train-outputs
        version: de4ff57e-3a95-44d1-bc06-a53be35ef8be
        mountPath: /labeled_dir
      - name: detection-f-US-KPI
        version: 2020-06-03-14-33-5dd3
        mountPath: /dataset

tasks:
- name: detr-train-8gpus-baseline-nvdatanorm-torgb-300epochs
  completions: 1
  env:
    MAGLEV_MULTIGPU_MODE: none
  gpus: 8
  # command: sleep infinity
  # command: bash -euxo pipefail -c "python -m torch.distributed.launch --nproc_per_node=8 --use_env sandbox/williamz/detr/main
  #   --dataset_root_sql /drivenet_1
  #   --dataset_root_img /drivenet_2
  #   --dataset_root_test /dataset
  #   --root_indices /pretrained_weights/labeled_sets/id_1_criterion_Max_SSD_num_labels_100000.npy
  #   --output_dir /out
  #   --batch_size 2"
  # command: python -m torch.distributed.launch --nproc_per_node=4 --use_env sandbox/williamz/detr/main.py
  #   --dataset_root_sql /drivenet_1
  #   --dataset_root_img /drivenet_2
  #   --dataset_root_test /dataset
  #   --output_dir /out
  #   --batch_size 4
  # command: bash -euxo pipefail -c "python -m torch.distributed.launch --nproc_per_node=8 --use_env sandbox/williamz/detr/main
  #   --dataset_root_sql /drivenet_1
  #   --dataset_root_img /drivenet_2
  #   --dataset_root_test /dataset
  #   --root_indices /labeled_dir/labeled_sets/id_1_criterion_Max_SSD_num_labels_50000.npy
  #   --output_dir /out
  #   --batch_size 2"
  command: bash -euxo pipefail -c "python -m torch.distributed.launch --nproc_per_node=8 --use_env sandbox/williamz/detr/main
    --num_queries 100
    --epochs 300
    --dataset_root_sql /drivenet_1
    --dataset_root_img /drivenet_2
    --dataset_root_test /dataset
    --root_indices /labeled_dir/labeled_sets/id_1_criterion_Max_SSD_num_labels_50000.npy
    --output_dir /out
    --batch_size 2"
  outputs:
    volumes:
    - name: train-outputs
      mountPath: /out


# dazel run //sandbox/williamz/detr/workflows:train_detr_8gpus -- -e maglev --remote_registry ngc