imagePullSecrets:
- nvcrio

defaults:
  # localImage: bazel/sandbox/williamz/secret_project/docker:image
  localImage: bazel/sandbox/williamz/detr/docker:image
  # localImage: bazel/detr/docker:detr_image
  # localImage: bazel/dlav/common:image
  inputs:
    volumes:
      - name: split-outputs
        version: 8493af65-a8ff-5489-b876-d2695b855014
        mountPath: /drivenet_1
      - name: d3l-detection-f-train
        version: 2020-03-10-16-13-7945
        mountPath: /drivenet_2
      - name: train-outputs
        version: 3ee9cdcf-ca6a-4645-9f7a-6b6fbdfaa760
        mountPath: /pretrained_weights
      - name: detection-f-US-KPI
        version: 2020-06-03-14-33-5dd3
        mountPath: /dataset

tasks:
- name: detr-train-4gpus
  completions: 1
  env:
    MAGLEV_MULTIGPU_MODE: none
  gpus: 4
  # command: sleep infinity
  command: bash -euxo pipefail -c "sandbox/williamz/detr/main
    --dataset_root_sql /drivenet_1
    --dataset_root_img /drivenet_2
    --dataset_root_test /dataset
    --output_dir /out
    --batch_size 4"
  # command: python -m torch.distributed.launch --nproc_per_node=4 --use_env sandbox/williamz/detr/main.py
  #   --dataset_root_sql /drivenet_1
  #   --dataset_root_img /drivenet_2
  #   --dataset_root_test /dataset
  #   --output_dir /out
  #   --batch_size 4
  outputs:
    volumes:
    - name: train-outputs
      mountPath: /out

